### ISSUE TITLE
ตอนรันเจอ error Execution failed for task ‘:thai_idcard_reader_flutter:compileDebugKotlin’.

### ISSUE THREAD

**Issue by thanapon1998** [11dj/thai_idcard_reader_flutter#3]
![1D6A1437-60BD-4D0A-A67D-6BF22FB1E162](https://user-images.githubusercontent.com/124644601/236613083-cb03b2d2-e4aa-4c08-8e3d-fc674e100485.jpeg)

รบกวนสอบถามครับ ผมติดตั้ง เวอร์ชั่น 0.0.6 เรียบร้อยไม่ติดปัญหาอะไรครับ 

แต่พอ run ขึ้น error ภาพ สามารถแก้ปัญหาอย่างไรได้บ้างครับ

**Comment by 11dj** [comment]
อยากทราบเวอร์ชั่น Flutter และ android ที่ใช้อยู่หน่อยครับ
 flutter doctor -v มาให้ดูหน่อยก็ได้ครับ

**Comment by thanapon1998** [comment]
![image](https://github.com/11dj/thai_idcard_reader_flutter/assets/124644601/a9bf73c0-c653-42ee-b1b3-ce5e16ad170c)

อันนี้ flutter doctor -v ครับ

**Comment by 11dj** [comment]
ผมอัพเดทเวอร์ชั่นเป็น 0.0.7 แล้วนะครับลองดูได้ครับ
