### ISSUE TITLE
Flutter Web สามารถใช้ได้ไหมครับ

### ISSUE THREAD

**Issue by nattapatwakhet** [11dj/thai_idcard_reader_flutter#5]
Flutter Web สามารถใช้ได้ไหมครับ หรือมีตัวอื่นแนะนำที่ใช้กับ web ได้ไหมครับ

**Comment by 11dj** [comment]
ยังไม่มีครับ 
library ของตัวเครื่องอ่านบัตร รับรองเฉพาะ Android ครับ
